### ISSUE TITLE
add option to exit non-zero if tests failed

### ISSUE THREAD

**Issue by mrooney** [TestArmada/flank#67] opened 2017-09-12 21:14 UTC
This would be a helpful configuration option that many tools provide, and would allow for more easily performing certain logic in CI environments if tests fail (without globbing and grepping xml files). Thanks for your consideration!

**Comment by bootstraponline** [comment] 2017-09-12 21:38
I agree, seems like a dupe of https://github.com/TestArmada/flank/issues/22

**Comment by renas** [comment] 2017-09-12 22:12
Good suggestion. We'll add it.

**Comment by mrooney** [comment] 2017-09-14 17:31
I see. Reading #22 more, it seems to be two issues conflated, one being that a command can fail and Flank will keep running, and the other that it doesn't exit non-zero in that case. So it seems like this part (exiting non-zero) might be easier than aborting the run in certain cases and could handled separately. But, up to you :)

**Comment by bootstraponline** [comment] 2017-09-14 17:47
Yeah, I guess it's more of a related issue than a dupe. I'll keep this open then.

**Closed** 2017-09-20 00:37 UTC
